[
  [
    ["wall"],
    ["wall"],
    ["wall"],
    ["door", "exit"],
    ["wall"],
    ["wall"],
    ["wall"],
    ["wall"],
    ["wall"],
  ],
  [["wall"], [], [], [], ["wall"], [], [], [], ["wall"]],
  [["wall"], ["wall"], ["wall"], [], ["wall"], [], ["wall"], [], ["wall"]],
  [["wall"], [], [], [], [], [], ["wall"], ["key"], ["wall"]],
  [
    ["wall"],
    [],
    ["wall"],
    ["wall"],
    ["wall"],
    ["wall"],
    ["wall"],
    ["wall"],
    ["wall"],
  ],
  [["wall"], [], ["wall"], [], ["wall"], [], [], [], ["wall"]],
  [["wall"], [], ["wall"], [], ["wall"], [], ["wall"], ["wall"], ["wall"]],
  [["wall"], [], [], [], [], [], [], [], ["wall"]],
  [
    ["wall"],
    ["wall"],
    ["wall"],
    ["door", "entrance"],
    ["wall"],
    ["wall"],
    ["wall"],
    ["wall"],
    ["wall"],
  ],
];
